# Plank configurations
# plank:
#   allow_cancellations: true # whether to delete ProwJobs' pod (true) or not (false) when new instances are triggered for the same PR
#   # used to link to job results for decorated jobs (with pod utilities)
#   default_decoration_config:
#     timeout: 14400000000000 # 4h in nano seconds
#     grace_period: 15000000000 # 15s in nano seconds
#     utility_images: # pull specs for container images used to construct job pods
#       clonerefs: gcr.io/k8s-prow/clonerefs:v20190221-d14461a
#       initupload: gcr.io/k8s-prow/initupload:v20190221-d14461a
#       entrypoint: gcr.io/k8s-prow/entrypoint:v20190221-d14461a
#       sidecar: gcr.io/k8s-prow/sidecar:v20190221-d14461a

# Sinker configurations (for cleanup)
sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 30m


# All the Tide configurations
tide:
  queries:
  - orgs:
    - aayushrangwala
  - repos:
    - aayushrangwala/k8s_prow_flask_cicd 
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase


# Default Labels template for jobs
job_labels_template: &job_labels_template
  preset-dind-enabled: "true"
  preset-service-account: "true"


# Periodic jobs 
periodics:
- interval: 30m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
- interval: 1m
  cluster: default
  agent: knative-build
  name: echo-test-knative-1
  build_spec:
    steps:
    - name: first
      image: busybox
      args: ["echo", "hello"]
    - name: second
      image: busybox
      args: ["echo", "world"]
- interval: 2m
  agent: knative-build
  name: echo-test-knative-new
  build_spec:
    steps:
    - name: first
      image: busybox
      args: ["echo", "hello"]
    - name: second
      image: busybox
      args: ["echo", "world"]



#Presubmits - madhunawandar
# Presubmit jobs
presubmits:
  madhurnawandar/k8s_prow_flask_cicd:
  - name: workflow-test-presubmit-knative
    agent: knative-build
    build_spec:
      steps:
      - name: first
        image: busybox
        args: ["echo", "hello"]
      - name: second
        image: busybox
        args: ["echo", "world"]
      - name: third
        image: busybox
        args: ["cat", "config.yaml"]


#presubmits - aayushrangwala
presubmits:
  aayushrangwala/k8s_prow_flask_cicd:
  - name: pull-test-infra-build-smoke
    cluster: default
    agent: knative-build
    always_run: true               # Run for every PR, or only when requested.
    skip_report: false             # Whether to skip setting a status on GitHub
    build_spec:
      steps:
      - name: first
        image: busybox
        args: ["echo", "hello"]
      - name: second
        image: busybox
        args: ["echo", "world"]

# Postsubmit jobs
postsubmits:
  aayushrangwala/k8s_prow_flask_cicd:
  - name: test-postsubmit
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
    max_concurrency: 10   # Run no more than this number concurrently.
    branches:             # Only run against these branches.
    - master
  - name: release-postsubmit
    agent: kubernetes
    max_concurrency: 10   # Run no more than this number concurrently.
    skip_report: false             # Whether to skip setting a status on GitHub.
    labels:
      <<: *job_labels_template
      preset-build-master: "true"
    spec:
      serviceAccountName: "default"
      containers:
      - image: docker.io/shekhawatsanjay/prow-ci-test
        args:
        - "pre"
        securityContext:
          privileged: true
        env:
        - name: workflow_chart
          value: release_workflow
    branches:             # Only run against these branches.
    - master
