apiVersion: v1
kind: Service
metadata:
  name: {{ required "an app name is required" .Values.appname }}-svc
  labels:
    run: {{ .Values.appname }}
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    run: {{ .Values.appname }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-dpl
spec:
  selector:
    matchLabels:
      run: flask-app
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        run: flask-app
    spec:
      containers:
      - name: flask-app
        image: {{ required "image is required" .Values.image }}
        ports:
        - containerPort: 5000
